/*==========================================================================

  FILE          MPMIntHalDevCfgData.c

  DESCRIPTION   This file contains the table that stores configuration 
                information about mpm mapped interrupt/gpios. MPM driver
                retrieves the index for this table from another mapping 
                table.

                Copyright © 2013 QUALCOMM Technologies Incorporated.
                All Rights Reserved.
                QUALCOMM Proprietary/GTDR

  $Header: //components/rel/core.adsp/2.2/power/mpm/config/asic/8084/MPMIntHalDevCfgData.c#1 $
===========================================================================*/

/* -----------------------------------------------------------------------
**                           INCLUDES
** ----------------------------------------------------------------------- */

#include "HALmpmint.h"
#include "HALmpmintInternal.h"

/* -----------------------------------------------------------------------
**                           DATA
** ----------------------------------------------------------------------- */

/*
 * Target-specific interrupt configurations
 */
HAL_mpmint_PlatformIntType devcfgMpmIntHalTable[] = 
{
  /*                             Trigger            GPIO          */
  /*                             -------  ----------------------- */
  HAL_MPMINT_DEFINE_TABLE_ENTRY( HIGH,    HAL_MPMINT_INVALID_GPIO ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( HIGH,    HAL_MPMINT_INVALID_GPIO ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( HIGH,    HAL_MPMINT_INVALID_GPIO ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  1  ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  5  ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  8  ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  9  ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  28 ),
  /*8*/
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  34  ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  40  ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  44  ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  48  ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  52  ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  55  ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  56  ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  58  ),
  /*16*/
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  60  ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  64  ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  67  ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  68  ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  69  ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  76  ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  77  ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  78  ),
  /*24*/
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  79  ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  84  ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  95  ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  102 ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  103 ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  104 ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  105 ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  107 ),
  /*32*/
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  109 ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  111 ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  113 ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  121 ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  122 ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  123 ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  131 ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( LOW,     HAL_MPMINT_INVALID_GPIO ),
  /*40*/
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  139 ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  141 ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( HIGH,    HAL_MPMINT_INVALID_GPIO ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( HIGH,    HAL_MPMINT_INVALID_GPIO ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( HIGH,    HAL_MPMINT_INVALID_GPIO ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( HIGH,    HAL_MPMINT_INVALID_GPIO ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( HIGH,    HAL_MPMINT_INVALID_GPIO ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( HIGH,    HAL_MPMINT_INVALID_GPIO ),
  /*48*/
  HAL_MPMINT_DEFINE_TABLE_ENTRY( HIGH,    HAL_MPMINT_INVALID_GPIO ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( HIGH,    HAL_MPMINT_INVALID_GPIO ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( HIGH,    HAL_MPMINT_INVALID_GPIO ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( HIGH,    HAL_MPMINT_INVALID_GPIO ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( HIGH,    HAL_MPMINT_INVALID_GPIO ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( HIGH,    HAL_MPMINT_INVALID_GPIO ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( HIGH,    HAL_MPMINT_INVALID_GPIO ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( HIGH,    HAL_MPMINT_INVALID_GPIO ),
  /*56*/
  HAL_MPMINT_DEFINE_TABLE_ENTRY( HIGH,    HAL_MPMINT_INVALID_GPIO ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( HIGH,    HAL_MPMINT_INVALID_GPIO ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( HIGH,    HAL_MPMINT_INVALID_GPIO ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( LOW,     HAL_MPMINT_INVALID_GPIO ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  HAL_MPMINT_INVALID_GPIO ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( RISING,  HAL_MPMINT_INVALID_GPIO ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( HIGH,    HAL_MPMINT_INVALID_GPIO ),
  HAL_MPMINT_DEFINE_TABLE_ENTRY( HIGH,    HAL_MPMINT_INVALID_GPIO ),
  /*64 - special entry to mark end of the table */
  HAL_MPMINT_DEFINE_TABLE_ENTRY( INVALID, HAL_MPMINT_INVALID_GPIO )
};

