/*=============================================================================
  @file smgr_test_main.c

  This file contains task of SMGR.

*******************************************************************************
*   Copyright (c) 2010, 2011 Qualcomm Technologies Incorporated.
*   All Rights Reserved.
*   Qualcomm Confidential and Proprietary
*
********************************************************************************/

/* $Header: //components/rel/ssc.adsp/2.4.1/adsp_proc/Sensors/smgr/src/common/sns_smgr_test.c#1 $ */
/* $DateTime: 2014/05/16 10:56:56 $ */
/* $Author: coresvc $ */

/*============================================================================
  EDIT HISTORY FOR FILE

  when        who  what, where, why
  ----------  ---  -----------------------------------------------------------
  2011-11-14  jhh  Updated alloc and free function calls to meet new API
  2011-06-10  sc   Moved the test suite to centralized unit test thread
  2011-04-25  br   changed test cases to verify the streaming with cancel and delete together
  2011-04-24  br   changed definition because of the new qmi version.
  2010-10-06  br   Changed SMR API from sns_smr_q_register() to sns_smr_register()
  2010-10-05  jb   CC3 initial build
  2010-08-27  sd   added sns_init_done in sns_smgr_test_init, updated SNS_SMGR_SVC_ID
  2010-07-7   SD   Initial version
============================================================================*/
/*----------------------------------------------------------------------------
 * Include Files
 * -------------------------------------------------------------------------*/

#include "sns_osa.h"
#include "sns_memmgr.h"

#include  <sns_smgr_api_v01.h>  /* Auto-generated by IDL */
#include  "sns_smgr_config.h"
#include  "sns_smgr_define.h"
#include  "sns_smgr.h"

#ifdef SNS_UNIT_TEST

#include "sns_test.h"

#define SNS_MODULE_SMGR_UNIT_TEST  SNS_MODULE_DSPS_TEST
/*----------------------------------------------------------------------------
 * Preprocessor Definitions and Constants
 * -------------------------------------------------------------------------*/
#define __SNS_MODULE__                 SNS_SMGR_TEST


/*----------------------------------------------------------------------------
 *  Variables
 * -------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------
 * Function Declarations and Documentation
 * -------------------------------------------------------------------------*/
/*  =============== sns_smgr_test1 ===============
    This function tests report request/response functionality
*/
uint32_t    ind_rcvd_cnt = 0;

void sns_smgr_test1()
{
  /* Load SOL with 3 items */
  sns_smr_header_s           msg_header;
  sns_smgr_periodic_report_req_msg_v01   *Msg_p;
//  sns_smgr_periodic_report_resp_msg_v01     RSP,  *Rsp_p;
  uint8_t                                    msg_body_size=0;
  OS_FLAGS	  sig_flags;
  uint8_t  err;
  boolean     test_done= FALSE;

  msg_body_size = sizeof(sns_smgr_periodic_report_req_msg_v01);
  Msg_p =(sns_smgr_periodic_report_req_msg_v01   *)sns_smr_msg_alloc(SNS_DBG_MOD_DSPS_SMGR,msg_body_size);

  Msg_p->ReportId = 19;
  Msg_p->Action = SNS_SMGR_REPORT_ACTION_ADD_V01;
  Msg_p->ReportRate = 30;
  Msg_p->BufferFactor = 2;
  Msg_p->Item_len = 3;

  Msg_p->Item[0].SensorId = SNS_SMGR_ID_ACCEL_V01;
  Msg_p->Item[0].DataType = SNS_SMGR_DATA_TYPE_PRIMARY_V01;
  Msg_p->Item[0].Sensitivity = 50;
  Msg_p->Item[0].Decimation = SNS_SMGR_DECIMATION_FILTER_V01;
  Msg_p->Item[0].MinSampleRate = 250; /* out of range, default to 0 */
  Msg_p->Item[0].StationaryOption = SNS_SMGR_REST_OPTION_REPORT_PRIOR_V01;
  Msg_p->Item[0].DoThresholdTest = 1;
  Msg_p->Item[0].ThresholdOutsideMinMax = 0;
  Msg_p->Item[0].ThresholdDelta = 0;
  Msg_p->Item[0].ThresholdAllAxes = 1;
  Msg_p->Item[0].ThresholdMinMax[0] = (int32_t)(0.731 * 65536);
  Msg_p->Item[0].ThresholdMinMax[1] = (int32_t)(1.009 * 65536);

  Msg_p->Item[1].SensorId = SNS_SMGR_ID_GYRO_V01;
  Msg_p->Item[1].DataType = SNS_SMGR_DATA_TYPE_PRIMARY_V01;
  Msg_p->Item[1].Sensitivity = 3;
  Msg_p->Item[1].Decimation = SNS_SMGR_DECIMATION_AVERAGE_V01;
  Msg_p->Item[1].MinSampleRate = 99;
  Msg_p->Item[1].StationaryOption = SNS_SMGR_REST_OPTION_REPORT_PRIOR_V01;
  Msg_p->Item[1].DoThresholdTest = 1;
  Msg_p->Item[1].ThresholdOutsideMinMax = 1;
  Msg_p->Item[1].ThresholdDelta = 0;
  Msg_p->Item[1].ThresholdAllAxes = 0;
  Msg_p->Item[1].ThresholdMinMax[0] = (int32_t)(0.731 * 65536);
  Msg_p->Item[1].ThresholdMinMax[1] = (int32_t)(1.009 * 65536);

  Msg_p->Item[2].SensorId = SNS_SMGR_ID_MAG_V01;
  Msg_p->Item[2].DataType = SNS_SMGR_DATA_TYPE_PRIMARY_V01;
  Msg_p->Item[2].Sensitivity = 1;
  Msg_p->Item[2].Decimation = SNS_SMGR_DECIMATION_RECENT_SAMPLE_V01;
  Msg_p->Item[2].MinSampleRate = 9;
  Msg_p->Item[2].StationaryOption = SNS_SMGR_REST_OPTION_REPORT_PRIOR_V01;
  Msg_p->Item[2].DoThresholdTest = 1;
  Msg_p->Item[2].ThresholdOutsideMinMax = 0;
  Msg_p->Item[2].ThresholdDelta = 1;
  Msg_p->Item[2].ThresholdAllAxes = 1;
  Msg_p->Item[2].ThresholdMinMax[0] = (int32_t)(1.009 * 65536); /* Test default */
  Msg_p->Item[2].ThresholdMinMax[1] = (int32_t)(0.731 * 65536);
  /* using  SNS_MODULE_SMGR_UNIT_TEST name for unit test */
  msg_header.src_module = SNS_MODULE_SMGR_UNIT_TEST;
  msg_header.dst_module = SNS_MODULE_DSPS_SMGR;
  msg_header.priority = SNS_SMR_MSG_PRI_LOW;

  msg_header.txn_id = 0x11;
  msg_header.ext_clnt_id = 0x22;
  msg_header.msg_type = SNS_SMR_MSG_TYPE_REQ;
  msg_header.svc_num = SNS_SMGR_SVC_ID_V01;
  msg_header.msg_id = SNS_SMGR_REPORT_REQ_V01;
  msg_header.body_len = msg_body_size;
  sns_smr_set_hdr ( &msg_header, Msg_p );
  sns_smr_send ( Msg_p );

  while ( 1 )
  {
    /* OS_FLAG_CONSUME will make the SMR clear the flag after the call */
     sig_flags = sns_os_sigs_pend ( sns_test_sig_grp, sns_test_sig_flag, OS_FLAG_WAIT_SET_ANY + OS_FLAG_CONSUME, 0, &err);
     if (sig_flags & sns_test_sig_flag)
     {
       uint8_t		*body_ptr;
       /* using  SNS_MODULE_SMGR_UNIT_TEST name for unit test */
       while ( NULL != (body_ptr = (uint8_t*)sns_smr_rcv (SNS_MODULE_SMGR_UNIT_TEST)))
       {
         sns_smgr_periodic_report_ind_msg_v01 *ind_ptr;
         sns_smr_get_hdr ( &msg_header, body_ptr );
         switch ( msg_header.msg_id )
         {
             static prev_ts = 0;
             uint32_t tm_now, ts_gap, us_gap;
           case SNS_SMGR_REPORT_RESP_V01:
                SMGR_LOG (" received SNS_SMGR_REPORT_RESP message %d \n");
                break;
           case SNS_SMGR_REPORT_IND_V01:
                ind_rcvd_cnt++;
                tm_now = sns_em_get_timestamp();
                ts_gap = tm_now - prev_ts;
                us_gap = sns_em_convert_dspstick_to_usec (ts_gap); 
//                SMGR_LOG ("==>Received NS_SMGR_REPORT_IND message(cnt=%d, ts=%d, gapts=%d, gapms=%.1f)\n",
//                   ind_rcvd_cnt, tm_now, ts_gap, (float)us_gap/1000 );
                ind_ptr = (sns_smgr_periodic_report_ind_msg_v01*)body_ptr;
                SMGR_LOG ("    ReportId =%d, status=%d, CurrentRate=%d, Item_len=%d\n",
                  ind_ptr->ReportId, ind_ptr->status, ind_ptr->CurrentRate, ind_ptr->Item_len);
                SMGR_LOG ("    SensorId =%d, Ts=%8d, x=%8d, y=%8d, z=%8d\n\n",
                  ind_ptr->Item[0].SensorId, ind_ptr->Item[0].TimeStamp, ind_ptr->Item[0].ItemData[0], ind_ptr->Item[0].ItemData[1], ind_ptr->Item[0].ItemData[2]);
                prev_ts = tm_now;
                break;
           default:
                SMGR_LOG (" received unknown message\n");
                break;
         }
         sns_smr_msg_free ( body_ptr );
       }
     }
     else
     {
         SMGR_LOG (" received unknown signal  \n");
     }
     if ( ind_rcvd_cnt > 10 )
     {
       SMGR_LOG ("\n===== SMGR test1 finished =====\n\n");
       break;
     }
  }

#if 0
  /* Delete the request */
  SMGR_LOG ("<====Now deleting the request(cnt=%d, ts=%d\n)",
                             ind_rcvd_cnt, sns_em_get_timestamp());
  msg_body_size = sizeof(sns_smgr_periodic_report_req_msg_v01);
  Msg_p =(sns_smgr_periodic_report_req_msg_v01   *)sns_smr_msg_alloc(SNS_DBG_MOD_DSPS_SMGR,msg_body_size);

  Msg_p->ReportId = 19;
  Msg_p->Action = SNS_SMGR_REPORT_ACTION_DELETE_V01;
  Msg_p->ReportRate = 81;
  Msg_p->BufferFactor = 2;
  Msg_p->Item_len = 1;

  Msg_p->Item[0].SensorId = SNS_SMGR_ID_ACCEL_V01;
  Msg_p->Item[0].DataType = SNS_SMGR_DATA_TYPE_SECONDARY_V01;
  Msg_p->Item[0].Sensitivity = 50;
  Msg_p->Item[0].Decimation = SNS_SMGR_DECIMATION_FILTER_V01;
  Msg_p->Item[0].MinSampleRate = 250; /* out of range, default to 0 */
  Msg_p->Item[0].StationaryOption = SNS_SMGR_REST_OPTION_REPORT_PRIOR_V01;
  Msg_p->Item[0].DoThresholdTest = 1;
  Msg_p->Item[0].ThresholdOutsideMinMax = 0;
  Msg_p->Item[0].ThresholdDelta = 0;
  Msg_p->Item[0].ThresholdAllAxes = 1;
  Msg_p->Item[0].ThresholdMinMax[0] = (int32_t)(0.731 * 65536);
  Msg_p->Item[0].ThresholdMinMax[1] = (int32_t)(1.009 * 65536);

  /* using  SNS_MODULE_SMGR_UNIT_TEST name for unit test */
  msg_header.src_module = SNS_MODULE_SMGR_UNIT_TEST;
  msg_header.dst_module = SNS_MODULE_DSPS_SMGR;
  msg_header.priority = SNS_SMR_MSG_PRI_LOW;

  msg_header.txn_id = 0x11;
  msg_header.ext_clnt_id = 0x22;
  msg_header.msg_type = SNS_SMR_MSG_TYPE_REQ;
  msg_header.svc_num = SNS_SMGR_SVC_ID_V01;
  msg_header.msg_id = SNS_SMGR_REPORT_REQ_V01;
  msg_header.body_len = msg_body_size;
  sns_smr_set_hdr ( &msg_header, Msg_p );
  sns_smr_send ( Msg_p );

  while ( 1 )
  {
    /* OS_FLAG_CONSUME will make the SMR clear the flag after the call */
     sig_flags = sns_os_sigs_pend ( sns_test_sig_grp, sns_test_sig_flag, OS_FLAG_WAIT_SET_ANY + OS_FLAG_CONSUME, 0, &err);
     if (sig_flags & sns_test_sig_flag)
     {
         uint8_t		*body_ptr;
         /* using  SNS_MODULE_SMGR_UNIT_TEST name for unit test */
         body_ptr = (uint8_t*)sns_smr_rcv (SNS_MODULE_SMGR_UNIT_TEST);
         sns_smr_get_hdr ( &msg_header, body_ptr );
         switch ( msg_header.msg_id )
         {
           case SNS_SMGR_REPORT_RESP_V01:
                SMGR_LOG (" received SNS_SMGR_REPORT_RESP message \n");
                test_done = TRUE;
                break;
           case SNS_SMGR_REPORT_IND_V01:
                SMGR_LOG (" received NS_SMGR_REPORT_IND message \n");
                break;
           default:
                SMGR_LOG (" received unknown message \n");
         }
         sns_smr_msg_free ( body_ptr );
     }
     else
     {
         SMGR_LOG (" received unknown signal  \n");
     }
     if ( test_done )
     {
        break;
     }
  }
#endif
}

/*  =============== sns_smgr_test2 ===============
    This function tests cancel request/response functionality
*/
void sns_smgr_test2()
{
  sns_smr_header_s           msg_header;
  void                      *Msg_p;
  uint8_t                      msg_body_size=0;
  OS_FLAGS	  sig_flags;
  uint8_t  err;
  boolean     test_done= FALSE;

  /* sns_smgr_cancel_req_msg_v01 message body is empty */
  Msg_p =(void *)sns_smr_msg_alloc(SNS_DBG_MOD_DSPS_SMGR,msg_body_size);


  /* using  SNS_MODULE_SMGR_UNIT_TEST name for unit test */
  msg_header.src_module = SNS_MODULE_SMGR_UNIT_TEST;
  msg_header.dst_module = SNS_MODULE_DSPS_SMGR;
  msg_header.priority = SNS_SMR_MSG_PRI_LOW;
  msg_header.txn_id = 0x11;
  msg_header.ext_clnt_id = 0x22;
  msg_header.msg_type = SNS_SMR_MSG_TYPE_REQ;
  msg_header.svc_num = SNS_SMGR_SVC_ID_V01;
  msg_header.msg_id = SNS_SMGR_CANCEL_REQ_V01;
  msg_header.body_len = msg_body_size;
  sns_smr_set_hdr ( &msg_header, Msg_p );
  sns_smr_send ( Msg_p );

  while ( 1 )
  {
     /* OS_FLAG_CONSUME will make the SMR clear the flag after the call */
     sig_flags = sns_os_sigs_pend ( sns_test_sig_grp, sns_test_sig_flag, OS_FLAG_WAIT_SET_ANY + OS_FLAG_CONSUME, 0, &err);
     if (sig_flags & sns_test_sig_flag)
     {
         uint8_t    *body_ptr;
         /* using  SNS_MODULE_SMGR_UNIT_TEST name for unit test */
         body_ptr = (uint8_t*)sns_smr_rcv (SNS_MODULE_SMGR_UNIT_TEST);
         sns_smr_get_hdr ( &msg_header, body_ptr );
         switch ( msg_header.msg_id )
         {
           case SNS_SMGR_REPORT_RESP_V01:
                SMGR_LOG (" received SNS_SMGR_REPORT_RESP message \n");
                break;
           case SNS_SMGR_REPORT_IND_V01:
                SMGR_LOG (" received NS_SMGR_REPORT_IND message \n");
                break;
           case SNS_SMGR_CANCEL_RESP_V01:
                SMGR_LOG (" received SNS_SMGR_CANCEL_RESP message \n");
                test_done= TRUE;
               break;
          default:
               SMGR_LOG (" received unknown message \n");
         }
         sns_smr_msg_free ( body_ptr );
     }
     else
     {
        SMGR_LOG (" received unknown signal  \n");
     }
     if ( test_done )
     {
        SMGR_LOG ("\n===== SMGR test2 finished =====\n\n");
        break;
     }
  }
}

/*  =============== sns_smgr_test3 ===============
    This function tests version request/response functionality
*/
void sns_smgr_test3()
{
  sns_smr_header_s           msg_header;
  void                      *Msg_p;
  uint8_t                      msg_body_size=0;
  OS_FLAGS	  sig_flags;
  uint8_t  err;
  boolean     test_done= FALSE;

  /* request msg body is empty */
  Msg_p =(void *)sns_smr_msg_alloc(SNS_DBG_MOD_DSPS_SMGR,msg_body_size);


  /* using  SNS_MODULE_SMGR_UNIT_TEST name for unit test */
  msg_header.src_module = SNS_MODULE_SMGR_UNIT_TEST;
  msg_header.dst_module = SNS_MODULE_DSPS_SMGR;
  msg_header.priority = SNS_SMR_MSG_PRI_LOW;
  msg_header.txn_id = 0x11;
  msg_header.ext_clnt_id = 0x22;
  msg_header.msg_type = SNS_SMR_MSG_TYPE_REQ;
  msg_header.svc_num = SNS_SMGR_SVC_ID_V01;
  msg_header.msg_id = SNS_SMGR_VERSION_REQ_V01;
  msg_header.body_len = msg_body_size;
  sns_smr_set_hdr ( &msg_header, Msg_p );
  sns_smr_send ( Msg_p );

  while ( 1 )
  {
     /* OS_FLAG_CONSUME will make the SMR clear the flag after the call */
     sig_flags = sns_os_sigs_pend ( sns_test_sig_grp, sns_test_sig_flag, OS_FLAG_WAIT_SET_ANY + OS_FLAG_CONSUME, 0, &err);
    if (sig_flags & sns_test_sig_flag)
    {
         uint8_t		*body_ptr;
         /* using  SNS_MODULE_SMGR_UNIT_TEST name for unit test */
         body_ptr = (uint8_t*)sns_smr_rcv (SNS_MODULE_SMGR_UNIT_TEST);
         sns_smr_get_hdr ( &msg_header, body_ptr );
         switch ( msg_header.msg_id )
         {
           case SNS_SMGR_REPORT_RESP_V01:
                SMGR_LOG (" received SNS_SMGR_REPORT_RESP message \n");
                break;
           case SNS_SMGR_REPORT_IND_V01:
                SMGR_LOG (" received NS_SMGR_REPORT_IND message \n");
                break;
           case SNS_SMGR_VERSION_RESP_V01:
               {
                 int16_t version= ((sns_common_version_resp_msg_v01 *)body_ptr)->interface_version_number;
                 SMGR_LOG (" received SNS_SMGR_VERSION_RESP message. version =%d \n", version);
                 test_done= TRUE;
                 break;
               }
           default:
                SMGR_LOG (" received unknown message \n");
         }
         sns_smr_msg_free ( body_ptr );
     }
     else
     {
        SMGR_LOG (" received unknown signal  \n");
     }
     if ( test_done )
     {
        SMGR_LOG ("\n===== SMGR test3 finished =====\n\n");
        break;
     }
  }

}

/*  =============== sns_smgr_test4 ===============
    This function tests calibration request/response functionality
*/
void sns_smgr_test4()
{
  sns_smr_header_s                 msg_header;
  sns_smgr_sensor_cal_req_msg_v01  *Msg_p;
  uint8_t                            msg_body_size=0;
  OS_FLAGS	  sig_flags;
  uint8_t  err;
  boolean     test_done= FALSE;

  msg_body_size = sizeof(sns_smgr_sensor_cal_req_msg_v01);
  Msg_p =(sns_smgr_sensor_cal_req_msg_v01 *)sns_smr_msg_alloc(SNS_DBG_MOD_DSPS_SMGR,msg_body_size);


  /* using  SNS_MODULE_SMGR_UNIT_TEST name for unit test */
  msg_header.src_module = SNS_MODULE_SMGR_UNIT_TEST;
  msg_header.dst_module = SNS_MODULE_DSPS_SMGR;
  msg_header.priority = SNS_SMR_MSG_PRI_LOW;
  msg_header.txn_id = 0x11;
  msg_header.ext_clnt_id = 0x22;
  msg_header.msg_type = SNS_SMR_MSG_TYPE_REQ;
  msg_header.svc_num = SNS_SMGR_SVC_ID_V01;
  msg_header.msg_id = SNS_SMGR_CAL_REQ_V01;
  msg_header.body_len = msg_body_size;

  Msg_p->SensorId = SNS_SMGR_ID_ACCEL_V01;
  //Msg_p->scale_error_len= 0;
  //Msg_p->zero_error_len = 3;
  //Msg_p->zero_error[0] = 0;
  //Msg_p->zero_error[1] = 0;
  //Msg_p->zero_error[2] = 0;

  sns_smr_set_hdr ( &msg_header, Msg_p );
  sns_smr_send ( Msg_p );

  while ( 1 )
  {
     /* OS_FLAG_CONSUME will make the SMR clear the flag after the call */
     sig_flags = sns_os_sigs_pend ( sns_test_sig_grp, sns_test_sig_flag, OS_FLAG_WAIT_SET_ANY + OS_FLAG_CONSUME, 0, &err);
     if (sig_flags & sns_test_sig_flag)
     {
         uint8_t   *body_ptr;
         /* using  SNS_MODULE_SMGR_UNIT_TEST name for unit test */
         body_ptr = (uint8_t*)sns_smr_rcv (SNS_MODULE_SMGR_UNIT_TEST);
         sns_smr_get_hdr ( &msg_header, body_ptr );
         switch ( msg_header.msg_id )
         {
           case SNS_SMGR_REPORT_RESP_V01:
                SMGR_LOG (" received SNS_SMGR_REPORT_RESP message \n");
                break;
           case SNS_SMGR_REPORT_IND_V01:
                SMGR_LOG (" received NS_SMGR_REPORT_IND message \n");
                break;
           case SNS_SMGR_CAL_RESP_V01:
                {
                  SMGR_LOG (" received SNS_SMGR_CAL_RESP message. \n");
                  test_done= TRUE;
                  break;
                }
           default:
                SMGR_LOG (" received unknown message \n");
         }
         sns_smr_msg_free ( body_ptr );
     }
     else
     {
        SMGR_LOG (" received unknown signal  \n");
     }
     if ( test_done )
     {
        SMGR_LOG ("\n===== SMGR test4 finished =====\n\n");
        break;
     }
  }


}

/*  =============== sns_smgr_test5 ===============
    This function tests all sensor info request/response functionality
*/
void sns_smgr_test5()
{
  sns_smr_header_s                       msg_header;
  void                                  *Msg_p;
  uint8_t                                  msg_body_size=0;
  OS_FLAGS	  sig_flags;
  uint8_t  err;
  boolean     test_done= FALSE;

  /* msg body is empty */
  msg_body_size =0;
  Msg_p =(void *)sns_smr_msg_alloc(SNS_DBG_MOD_DSPS_SMGR,msg_body_size);


  /* using  SNS_MODULE_SMGR_UNIT_TEST name for unit test */
  msg_header.src_module = SNS_MODULE_SMGR_UNIT_TEST;
  msg_header.dst_module = SNS_MODULE_DSPS_SMGR;
  msg_header.priority = SNS_SMR_MSG_PRI_LOW;
  msg_header.txn_id = 0x11;
  msg_header.ext_clnt_id = 0x22;
  msg_header.msg_type = SNS_SMR_MSG_TYPE_REQ;
  msg_header.svc_num = SNS_SMGR_SVC_ID_V01;
  msg_header.msg_id = SNS_SMGR_ALL_SENSOR_INFO_REQ_V01;
  msg_header.body_len = msg_body_size;

  sns_smr_set_hdr ( &msg_header, Msg_p );
  sns_smr_send ( Msg_p );

  while ( 1 )
  {
      /* OS_FLAG_CONSUME will make the SMR clear the flag after the call */
     sig_flags = sns_os_sigs_pend ( sns_test_sig_grp, sns_test_sig_flag, OS_FLAG_WAIT_SET_ANY + OS_FLAG_CONSUME, 0, &err);
     if (sig_flags & sns_test_sig_flag)
     {
         uint8_t     *body_ptr;
         /* using  SNS_MODULE_SMGR_UNIT_TEST name for unit test */
         body_ptr = (uint8_t*)sns_smr_rcv (SNS_MODULE_SMGR_UNIT_TEST);
         sns_smr_get_hdr ( &msg_header, body_ptr );
         switch ( msg_header.msg_id )
         {
           case SNS_SMGR_REPORT_RESP_V01:
                SMGR_LOG (" received SNS_SMGR_REPORT_RESP message \n");
                break;
           case SNS_SMGR_REPORT_IND_V01:
                SMGR_LOG (" received NS_SMGR_REPORT_IND message \n");
                break;
           case SNS_SMGR_ALL_SENSOR_INFO_RESP_V01:
                {
                  sns_smgr_all_sensor_info_resp_msg_v01 *resp=(sns_smgr_all_sensor_info_resp_msg_v01 *)body_ptr;
                  SMGR_LOG (" received SNS_SMGR_ALL_SENSOR_INFO_RESP message. %d sensor %s\n", resp->SensorInfo_len,
                  resp->SensorInfo[0].SensorShortName );
                  test_done= TRUE;
                  break;
                }
          default:
                SMGR_LOG (" received unknown message \n");
         }
         sns_smr_msg_free ( body_ptr );
     }
     else
     {
        SMGR_LOG (" received unknown signal  \n");
     }
     if ( test_done )
     {
        SMGR_LOG ("\n===== SMGR test5 finished =====\n\n");
        break;
     }
  }


}

/*  =============== sns_smgr_test6 ===============
    This function tests single sensor info request/response functionality
*/
void sns_smgr_test6()
{
  sns_smr_header_s                         msg_header;
  sns_smgr_single_sensor_info_req_msg_v01 *Msg_p;
  uint8_t                                    msg_body_size=0;
  OS_FLAGS	  sig_flags;
  uint8_t  err;
  boolean     test_done= FALSE;

  msg_body_size =sizeof(sns_smgr_single_sensor_info_req_msg_v01);
  Msg_p =(sns_smgr_single_sensor_info_req_msg_v01 *)sns_smr_msg_alloc(SNS_DBG_MOD_DSPS_SMGR,msg_body_size);


  /* using  SNS_MODULE_SMGR_UNIT_TEST name for unit test */
  msg_header.src_module = SNS_MODULE_SMGR_UNIT_TEST;
  msg_header.dst_module = SNS_MODULE_DSPS_SMGR;
  msg_header.priority = SNS_SMR_MSG_PRI_LOW;
  msg_header.txn_id = 0x11;
  msg_header.ext_clnt_id = 0x22;
  msg_header.msg_type = SNS_SMR_MSG_TYPE_REQ;
  msg_header.svc_num = SNS_SMGR_SVC_ID_V01;
  msg_header.msg_id = SNS_SMGR_SINGLE_SENSOR_INFO_REQ_V01;
  msg_header.body_len = msg_body_size;
  Msg_p->SensorID = SNS_SMGR_ID_ACCEL_V01;

  sns_smr_set_hdr ( &msg_header, Msg_p );
  sns_smr_send ( Msg_p );

  while ( 1 )
  {
     /* OS_FLAG_CONSUME will make the SMR clear the flag after the call */
     sig_flags = sns_os_sigs_pend ( sns_test_sig_grp, sns_test_sig_flag, OS_FLAG_WAIT_SET_ANY + OS_FLAG_CONSUME, 0, &err);
     if (sig_flags & sns_test_sig_flag)
     {
         uint8_t    *body_ptr;
         /* using  SNS_MODULE_SMGR_UNIT_TEST name for unit test */
         body_ptr = (uint8_t*)sns_smr_rcv (SNS_MODULE_SMGR_UNIT_TEST);
         sns_smr_get_hdr ( &msg_header, body_ptr );
         switch ( msg_header.msg_id )
         {
           case SNS_SMGR_REPORT_RESP_V01:
                SMGR_LOG (" received SNS_SMGR_REPORT_RESP message \n");
                break;
           case SNS_SMGR_REPORT_IND_V01:
                SMGR_LOG (" received NS_SMGR_REPORT_IND message \n");
                break;
           case SNS_SMGR_SINGLE_SENSOR_INFO_RESP_V01:
                {
                  sns_smgr_single_sensor_info_resp_msg_v01 *resp=(sns_smgr_single_sensor_info_resp_msg_v01 *)body_ptr;
                  SMGR_LOG (" received SNS_SMGR_SINGLE_SENSOR_INFO_RESP message. %d sensor %s\n", resp->SensorInfo.data_type_info_len,
                        resp->SensorInfo.data_type_info[0].SensorName );
                  test_done= TRUE;
                  break;
                }
           default:
               SMGR_LOG (" received unknown message \n");
         }
         sns_smr_msg_free ( body_ptr );
     }
     else
     {
         SMGR_LOG (" received unknown signal  \n");
     }
     if ( test_done )
     {
        SMGR_LOG ("\n===== SMGR test6 finished =====\n\n");
        break;
     }
  }


}

/*  =============== sns_smgr_test7 ===============
    This function tests sensor test request/response functionality
*/
void sns_smgr_test7()
{
  sns_smr_header_s                         msg_header;
  void                                    *Msg_p;
  uint8_t                                    msg_body_size=0;
  OS_FLAGS	  sig_flags;
  uint8_t  err;
  boolean     test_done= FALSE;

  /* msg body is empty */
  msg_body_size =0;
  Msg_p =(void *)sns_smr_msg_alloc(SNS_DBG_MOD_DSPS_SMGR,msg_body_size);

    /* using  SNS_MODULE_SMGR_UNIT_TEST name for unit test */
  msg_header.src_module = SNS_MODULE_SMGR_UNIT_TEST;
  msg_header.dst_module = SNS_MODULE_DSPS_SMGR;
  msg_header.priority = SNS_SMR_MSG_PRI_LOW;
  msg_header.txn_id = 0x11;
  msg_header.ext_clnt_id = 0x22;
  msg_header.msg_type = SNS_SMR_MSG_TYPE_REQ;
  msg_header.svc_num = SNS_SMGR_SVC_ID_V01;
  msg_header.msg_id = SNS_SMGR_SENSOR_TEST_REQ_V01;
  msg_header.body_len = msg_body_size;

  sns_smr_set_hdr ( &msg_header, Msg_p );
  sns_smr_send ( Msg_p );

  while ( 1 )
  {
     /* OS_FLAG_CONSUME will make the SMR clear the flag after the call */
     sig_flags = sns_os_sigs_pend ( sns_test_sig_grp, sns_test_sig_flag, OS_FLAG_WAIT_SET_ANY + OS_FLAG_CONSUME, 0, &err);
     if (sig_flags & sns_test_sig_flag)
     {
         uint8_t     *body_ptr;
         /* using  SNS_MODULE_SMGR_UNIT_TEST name for unit test */
         body_ptr = (uint8_t*)sns_smr_rcv (SNS_MODULE_SMGR_UNIT_TEST);
         sns_smr_get_hdr ( &msg_header, body_ptr );
         switch ( msg_header.msg_id )
         {
           case SNS_SMGR_REPORT_RESP_V01:
                SMGR_LOG (" received SNS_SMGR_REPORT_RESP message \n");
                break;
           case SNS_SMGR_REPORT_IND_V01:
                SMGR_LOG (" received NS_SMGR_REPORT_IND message \n");
                break;
           case SNS_SMGR_SENSOR_TEST_RESP_V01:
                {
                  sns_smgr_sensor_test_resp_msg_v01 *resp=(sns_smgr_sensor_test_resp_msg_v01 *)body_ptr;
                  SMGR_LOG (" received sns_smgr_sensor_test_resp_msg . %d sensor can command sensor %d\n", resp->result[0].SensorID, resp->result[0].CanCommandSensor );
                  test_done= TRUE;
                  break;
                }
                default:
                SMGR_LOG (" received unknown message \n");
         }
         sns_smr_msg_free ( body_ptr );
     }
     else
     {
        SMGR_LOG (" received unknown signal  \n");
     }
     if ( test_done )
     {
        SMGR_LOG ("\n===== SMGR test7 finished =====\n\n");
        break;
     }
  }


}

/*  =============== sns_smgr_test8 ===============
    This function tests power status request/response/indication functionality
*/
void sns_smgr_test8()
{
  sns_smr_header_s                          msg_header;
  sns_smgr_sensor_power_status_req_msg_v01 *Msg_p;
  uint8_t                                     msg_body_size=0;
  OS_FLAGS	  sig_flags;
  uint8_t  err;
  boolean     test_done= FALSE;

  msg_body_size =sizeof(sns_smgr_sensor_power_status_req_msg_v01);
  Msg_p =(sns_smgr_sensor_power_status_req_msg_v01 *)sns_smr_msg_alloc(SNS_DBG_MOD_DSPS_SMGR,msg_body_size);


  /* using  SNS_MODULE_SMGR_UNIT_TEST name for unit test */
  msg_header.src_module = SNS_MODULE_SMGR_UNIT_TEST;
  msg_header.dst_module = SNS_MODULE_DSPS_SMGR;
  msg_header.priority = SNS_SMR_MSG_PRI_LOW;
  msg_header.txn_id = 0x11;
  msg_header.ext_clnt_id = 0x22;
  msg_header.msg_type = SNS_SMR_MSG_TYPE_REQ;
  msg_header.svc_num = SNS_SMGR_SVC_ID_V01;
  msg_header.msg_id = SNS_SMGR_SENSOR_POWER_STATUS_REQ_V01;
  msg_header.body_len = msg_body_size;
  Msg_p->ReportId = 10;
  /* add report */
  Msg_p->Action = 0;


  sns_smr_set_hdr ( &msg_header, Msg_p );
  sns_smr_send ( Msg_p );

  while ( 1 )
  {
     /* OS_FLAG_CONSUME will make the SMR clear the flag after the call */
     sig_flags = sns_os_sigs_pend ( sns_test_sig_grp, sns_test_sig_flag, OS_FLAG_WAIT_SET_ANY + OS_FLAG_CONSUME, 0, &err);
     if (sig_flags & sns_test_sig_flag)
     {
         uint8_t  *body_ptr;
         /* using  SNS_MODULE_SMGR_UNIT_TEST name for unit test */
         body_ptr = (uint8_t*)sns_smr_rcv (SNS_MODULE_SMGR_UNIT_TEST);
         sns_smr_get_hdr ( &msg_header, body_ptr );
         switch ( msg_header.msg_id )
         {
           case SNS_SMGR_REPORT_RESP_V01:
                SMGR_LOG (" received SNS_SMGR_REPORT_RESP message \n");
                break;
           case SNS_SMGR_REPORT_IND_V01:
                SMGR_LOG (" received NS_SMGR_REPORT_IND message \n");
                break;
           case SNS_SMGR_SENSOR_POWER_STATUS_RESP_V01:
                {
                  SMGR_LOG (" received SNS_SMGR_SENSOR_POWER_STATUS_RESP message. \n");
                  test_done= TRUE;
                  break;
                }
           case SNS_SMGR_SENSOR_POWER_STATUS_IND_V01:
                SMGR_LOG (" received SNS_SMGR_SENSOR_POWER_STATUS_IND message \n");
                break;
           default:
                SMGR_LOG (" received unknown message \n");
         }
         sns_smr_msg_free ( body_ptr );
     }
     else
     {
        SMGR_LOG (" received unknown signal  \n");
     }
     if ( test_done )
     {
        SMGR_LOG ("\n===== SMGR test8 finished =====\n\n");
        break;
     }
  }
}


/*  =============== sns_smgr_test9 ===============
    This function tests power control request/response functionality
*/
void sns_smgr_test9()
{
  sns_smr_header_s                           msg_header;
  sns_smgr_sensor_power_control_req_msg_v01 *Msg_p;
  uint8_t                                      msg_body_size=0;
  OS_FLAGS	  sig_flags;
  uint8_t  err;
  boolean     test_done= FALSE;

  msg_body_size =sizeof(sns_smgr_sensor_power_control_req_msg_v01);
  Msg_p =(sns_smgr_sensor_power_control_req_msg_v01 *)sns_smr_msg_alloc(SNS_DBG_MOD_DSPS_SMGR,msg_body_size);


  /* using  SNS_MODULE_SMGR_UNIT_TEST name for unit test */
  msg_header.src_module = SNS_MODULE_SMGR_UNIT_TEST;
  msg_header.dst_module = SNS_MODULE_DSPS_SMGR;
  msg_header.priority = SNS_SMR_MSG_PRI_LOW;
  msg_header.txn_id = 0x11;
  msg_header.ext_clnt_id = 0x22;
  msg_header.msg_type = SNS_SMR_MSG_TYPE_REQ;
  msg_header.svc_num = SNS_SMGR_SVC_ID_V01;
  msg_header.msg_id = SNS_SMGR_SENSOR_POWER_CONTROL_REQ_V01;
  msg_header.body_len = msg_body_size;
  Msg_p->SensorID = 10;
  /* add report */
  Msg_p->Action = 0;


  sns_smr_set_hdr ( &msg_header, Msg_p );
  sns_smr_send ( Msg_p );

  while ( 1 )
  {
     /* OS_FLAG_CONSUME will make the SMR clear the flag after the call */
     sig_flags = sns_os_sigs_pend ( sns_test_sig_grp, sns_test_sig_flag, OS_FLAG_WAIT_SET_ANY + OS_FLAG_CONSUME, 0, &err);
     if (sig_flags & sns_test_sig_flag)
     {
         uint8_t    *body_ptr;
         /* using  SNS_MODULE_SMGR_UNIT_TEST name for unit test */
         body_ptr = (uint8_t*)sns_smr_rcv (SNS_MODULE_SMGR_UNIT_TEST);
         sns_smr_get_hdr ( &msg_header, body_ptr );
         switch ( msg_header.msg_id )
         {
           case SNS_SMGR_REPORT_RESP_V01:
                SMGR_LOG (" received SNS_SMGR_REPORT_RESP message \n");
                break;
           case SNS_SMGR_REPORT_IND_V01:
                SMGR_LOG (" received NS_SMGR_REPORT_IND message \n");
                break;
           case SNS_SMGR_SENSOR_POWER_CONTROL_RESP_V01:
                {
                  SMGR_LOG (" received SNS_SMGR_SENSOR_POWER_CONTROL_RESP message. \n");
                  test_done= TRUE;
                  break;
                }
       	   default:
                SMGR_LOG (" received unknown message \n");
         }
         sns_smr_msg_free ( body_ptr );
     }
     else
     {
         SMGR_LOG (" received unknown signal  \n");
     }
     if ( test_done )
     {
        SMGR_LOG ("\n===== SMGR test9 finished =====\n\n");
        break;
     }
  }
}

/*  =============== sns_smgr_test10 ===============
    This function tests report request(ADD)/response /
    request(DELETE)/response functionality
*/
void sns_smgr_test10()
{
  /* Load SOL with 3 items */
  sns_smr_header_s           msg_header;
  sns_smgr_periodic_report_req_msg_v01   *Msg_p;
//  sns_smgr_periodic_report_resp_msg_v01     RSP,  *Rsp_p;
  uint8_t                                    msg_body_size=0;
  OS_FLAGS	  sig_flags;
  uint8_t  err;
  boolean     test_done= FALSE, add_done = FALSE;

  msg_body_size = sizeof(sns_smgr_periodic_report_req_msg_v01);
  Msg_p =(sns_smgr_periodic_report_req_msg_v01   *)sns_smr_msg_alloc(SNS_DBG_MOD_DSPS_SMGR,msg_body_size);

  Msg_p->ReportId = 19;
  Msg_p->Action = SNS_SMGR_REPORT_ACTION_ADD_V01;
  Msg_p->ReportRate = 81;
  Msg_p->BufferFactor = 2;
  Msg_p->Item_len = 1;

  Msg_p->Item[0].SensorId = SNS_SMGR_ID_ACCEL_V01;
  Msg_p->Item[0].DataType = SNS_SMGR_DATA_TYPE_SECONDARY_V01;
  Msg_p->Item[0].Sensitivity = 50;
  Msg_p->Item[0].Decimation = SNS_SMGR_DECIMATION_FILTER_V01;
  Msg_p->Item[0].MinSampleRate = 250; /* out of range, default to 0 */
  Msg_p->Item[0].StationaryOption = SNS_SMGR_REST_OPTION_REPORT_PRIOR_V01;
  Msg_p->Item[0].DoThresholdTest = 1;
  Msg_p->Item[0].ThresholdOutsideMinMax = 0;
  Msg_p->Item[0].ThresholdDelta = 0;
  Msg_p->Item[0].ThresholdAllAxes = 1;
  Msg_p->Item[0].ThresholdMinMax[0] = (int32_t)(0.731 * 65536);
  Msg_p->Item[0].ThresholdMinMax[1] = (int32_t)(1.009 * 65536);

  
  
  /* using  SNS_MODULE_SMGR_UNIT_TEST name for unit test */
  msg_header.src_module = SNS_MODULE_SMGR_UNIT_TEST;
  msg_header.dst_module = SNS_MODULE_DSPS_SMGR;
  msg_header.priority = SNS_SMR_MSG_PRI_LOW;

  msg_header.txn_id = 0x11;
  msg_header.ext_clnt_id = 0x22;
  msg_header.msg_type = SNS_SMR_MSG_TYPE_REQ;
  msg_header.svc_num = SNS_SMGR_SVC_ID_V01;
  msg_header.msg_id = SNS_SMGR_REPORT_REQ_V01;
  msg_header.body_len = msg_body_size;
  sns_smr_set_hdr ( &msg_header, Msg_p );
  sns_smr_send ( Msg_p );

  while ( 1 )
  {
    /* OS_FLAG_CONSUME will make the SMR clear the flag after the call */
     sig_flags = sns_os_sigs_pend ( sns_test_sig_grp, sns_test_sig_flag, OS_FLAG_WAIT_SET_ANY + OS_FLAG_CONSUME, 0, &err);
     if (sig_flags & sns_test_sig_flag)
     {
         uint8_t		*body_ptr;
         /* using  SNS_MODULE_SMGR_UNIT_TEST name for unit test */
         body_ptr = (uint8_t*)sns_smr_rcv (SNS_MODULE_SMGR_UNIT_TEST);
         sns_smr_get_hdr ( &msg_header, body_ptr );
         switch ( msg_header.msg_id )
         {
           case SNS_SMGR_REPORT_RESP_V01:
                SMGR_LOG (" received SNS_SMGR_REPORT_RESP message \n");
                add_done = TRUE;
                break;
           case SNS_SMGR_REPORT_IND_V01:
                SMGR_LOG (" received NS_SMGR_REPORT_IND message \n");
                break;
           default:
                SMGR_LOG (" received unknown message \n");
         }
         sns_smr_msg_free ( body_ptr );
     }
     else
     {
         SMGR_LOG (" received unknown signal  \n");
     }
     if ( add_done )
     {
        break;
     }
  }

  msg_body_size = sizeof(sns_smgr_periodic_report_req_msg_v01);
  Msg_p =(sns_smgr_periodic_report_req_msg_v01   *)sns_smr_msg_alloc(SNS_DBG_MOD_DSPS_SMGR,msg_body_size);

  Msg_p->ReportId = 19;
  Msg_p->Action = SNS_SMGR_REPORT_ACTION_DELETE_V01;
  Msg_p->ReportRate = 81;
  Msg_p->BufferFactor = 2;
  Msg_p->Item_len = 1;

  Msg_p->Item[0].SensorId = SNS_SMGR_ID_ACCEL_V01;
  Msg_p->Item[0].DataType = SNS_SMGR_DATA_TYPE_SECONDARY_V01;
  Msg_p->Item[0].Sensitivity = 50;
  Msg_p->Item[0].Decimation = SNS_SMGR_DECIMATION_FILTER_V01;
  Msg_p->Item[0].MinSampleRate = 250; /* out of range, default to 0 */
  Msg_p->Item[0].StationaryOption = SNS_SMGR_REST_OPTION_REPORT_PRIOR_V01;
  Msg_p->Item[0].DoThresholdTest = 1;
  Msg_p->Item[0].ThresholdOutsideMinMax = 0;
  Msg_p->Item[0].ThresholdDelta = 0;
  Msg_p->Item[0].ThresholdAllAxes = 1;
  Msg_p->Item[0].ThresholdMinMax[0] = (int32_t)(0.731 * 65536);
  Msg_p->Item[0].ThresholdMinMax[1] = (int32_t)(1.009 * 65536);

  /* using  SNS_MODULE_SMGR_UNIT_TEST name for unit test */
  msg_header.src_module = SNS_MODULE_SMGR_UNIT_TEST;
  msg_header.dst_module = SNS_MODULE_DSPS_SMGR;
  msg_header.priority = SNS_SMR_MSG_PRI_LOW;

  msg_header.txn_id = 0x11;
  msg_header.ext_clnt_id = 0x22;
  msg_header.msg_type = SNS_SMR_MSG_TYPE_REQ;
  msg_header.svc_num = SNS_SMGR_SVC_ID_V01;
  msg_header.msg_id = SNS_SMGR_REPORT_REQ_V01;
  msg_header.body_len = msg_body_size;
  sns_smr_set_hdr ( &msg_header, Msg_p );
  sns_smr_send ( Msg_p );

  while ( 1 )
  {
    /* OS_FLAG_CONSUME will make the SMR clear the flag after the call */
     sig_flags = sns_os_sigs_pend ( sns_test_sig_grp, sns_test_sig_flag, OS_FLAG_WAIT_SET_ANY + OS_FLAG_CONSUME, 0, &err);
     if (sig_flags & sns_test_sig_flag)
     {
         uint8_t		*body_ptr;
         /* using  SNS_MODULE_SMGR_UNIT_TEST name for unit test */
         body_ptr = (uint8_t*)sns_smr_rcv (SNS_MODULE_SMGR_UNIT_TEST);
         sns_smr_get_hdr ( &msg_header, body_ptr );
         switch ( msg_header.msg_id )
         {
           case SNS_SMGR_REPORT_RESP_V01:
                SMGR_LOG (" received SNS_SMGR_REPORT_RESP message \n");
                test_done = TRUE;
                break;
           case SNS_SMGR_REPORT_IND_V01:
                SMGR_LOG (" received NS_SMGR_REPORT_IND message \n");
                break;
           default:
                SMGR_LOG (" received unknown message \n");
         }
         sns_smr_msg_free ( body_ptr );
     }
     else
     {
         SMGR_LOG (" received unknown signal  \n");
     }
     if ( test_done )
     {
        SMGR_LOG ("\n===== SMGR test10 finished =====\n\n");
        break;
     }
  }
}

void
sns_smgr_test_main()
{
  sns_smgr_test1();
  sns_smgr_test2();

  sns_smgr_test3();
  sns_smgr_test4();
  sns_smgr_test5();

  sns_smgr_test6();
  sns_smgr_test7();
  sns_smgr_test8();
  sns_smgr_test9();
  sns_smgr_test10();  
}

#endif /*SNS_SMGR_UNIT_TEST*/
