
/*=============================================================================
  @file smgr_test_main.c
 
  This file contains test drivers for offline unit test of SMGR modules. It is 
  not used when SMGR is integrated with the rest of DSPS.
 
*******************************************************************************
*   Copyright (c) 2010 Qualcomm Technologies Incorporated. 
*   All Rights Reserved.
*   Qualcomm Confidential and Proprietary
*
********************************************************************************/

/* $Header: //components/rel/ssc.adsp/2.4.1/adsp_proc/Sensors/smgr/src/common/sns_smgr_test_main.c#1 $ */
/* $DateTime: 2014/05/16 10:56:56 $ */
/* $Author: coresvc $ */

/*============================================================================
  EDIT HISTORY FOR FILE

  when        who  what, where, why
  ----------  ---  -----------------------------------------------------------
  2010-07-09  JB   Follow API changes
  2010-06-25  JB   Added tests for heartbeat scheduling
  2010-06-11  JB   Initial version
============================================================================*/



#include "sns_osa.h"
#include "sns_memmgr.h"

#include  <sns_smgr_api_v01.h>   /* Auto-generated by IDL */
#include  <sns_smgr_config.h>
#include "sns_smgr_define.h"


smgr_rpt_spec_s *Head, *New;


//int main(int argc, char* argv[])

int sns_smgr_test( void )
{

  sns_smgr_sol_init();
  sns_smgr_sensor_init();


#define TEST2
#define TEST3
//#define TEST4
//#define TEST5
#define TEST6
#define TEST7
#define TEST8

#ifdef TEST2
{
  /* Load SOL with 3 items */
  sns_smgr_MsgHeader_s           HDR, *Hdr_p;
  sns_smgr_periodic_report_req_msg_v01  MSG,  *Msg_p;
  sns_smgr_periodic_report_resp_msg_v01     RSP,  *Rsp_p;
  int8_t  Dummy;
  
  Hdr_p = &HDR;
  Msg_p = &MSG;
  Rsp_p = &RSP;
  
  Hdr_p->client_id = 75;
  Hdr_p->priority = SNS_SMGR_REPORT_PRIORITY_LOW;

  Msg_p->ReportId = 19;
  Msg_p->Action = SNS_SMGR_REPORT_ACTION_ADD;
  Msg_p->ReportRate = 81;
  Msg_p->BufferFactor = 2;
  Msg_p->Item_len = 3;
  
  Msg_p->Item[0].SensorId = SNS_SMGR_ID_ACCEL;  
  Msg_p->Item[0].DataType = SNS_SMGR_DATA_TYPE_TEMPERATURE;
  Msg_p->Item[0].Sensitivity = 50;
  Msg_p->Item[0].Decimation = SNS_SMGR_DECIMATION_FILTER;
  Msg_p->Item[0].MinSampleRate = 250; /* out of range, default to 0 */
  Msg_p->Item[0].StationaryOption = SNS_SMGR_REST_OPTION_REPORT_PRIOR;
  Msg_p->Item[0].DoThresholdTest = 1;
  Msg_p->Item[0].ThresholdOutsideMinMax = 0;
  Msg_p->Item[0].ThresholdDelta = 0;
  Msg_p->Item[0].ThresholdAllAxes = 1;
  Msg_p->Item[0].ThresholdMinMax[0] = (int32_t)(0.731 * 65536);
  Msg_p->Item[0].ThresholdMinMax[1] = (int32_t)(1.009 * 65536);
  
  Msg_p->Item[1].SensorId = SNS_SMGR_ID_GYRO;  
  Msg_p->Item[1].DataType = SNS_SMGR_DATA_TYPE_ENG_UNITS;
  Msg_p->Item[1].Sensitivity = 3;
  Msg_p->Item[1].Decimation = SNS_SMGR_DECIMATION_AVERAGE;
  Msg_p->Item[1].MinSampleRate = 99;
  Msg_p->Item[1].StationaryOption = SNS_SMGR_REST_OPTION_REPORT_PRIOR;
  Msg_p->Item[1].DoThresholdTest = 1;
  Msg_p->Item[1].ThresholdOutsideMinMax = 1;
  Msg_p->Item[1].ThresholdDelta = 0;
  Msg_p->Item[1].ThresholdAllAxes = 0;
  Msg_p->Item[1].ThresholdMinMax[0] = (int32_t)(0.731 * 65536);
  Msg_p->Item[1].ThresholdMinMax[1] = (int32_t)(1.009 * 65536);
  
  Msg_p->Item[2].SensorId = SNS_SMGR_ID_MAG;  
  Msg_p->Item[2].DataType = SNS_SMGR_DATA_TYPE_ENG_UNITS;
  Msg_p->Item[2].Sensitivity = 1;
  Msg_p->Item[2].Decimation = SNS_SMGR_DECIMATION_RECENT_SAMPLE;
  Msg_p->Item[2].MinSampleRate = 9;
  Msg_p->Item[2].StationaryOption = SNS_SMGR_REST_OPTION_REPORT_PRIOR;
  Msg_p->Item[2].DoThresholdTest = 1;
  Msg_p->Item[2].ThresholdOutsideMinMax = 0;
  Msg_p->Item[2].ThresholdDelta = 1;
  Msg_p->Item[2].ThresholdAllAxes = 1;
  Msg_p->Item[2].ThresholdMinMax[0] = (int32_t)(1.009 * 65536); /* Test default */
  Msg_p->Item[2].ThresholdMinMax[1] = (int32_t)(0.731 * 65536);

  
  sns_smgr_proc_periodic_req_msg( Hdr_p, Msg_p, Rsp_p );
  
  Dummy = 1;
}
#endif  /* TEST2 */	
  
#ifdef TEST3
{
  /* Add another report. Preset size of available space so this report
     will fail for lack of memory. Repeat with different amount of space
     each time so that each place in the code where lack of space
     is detected gets an opportunity to fail gracefully */
  sns_smgr_MsgHeader_s           HDR, *Hdr_p;
  sns_smgr_periodic_report_req_msg_v01  MSG,  *Msg_p;
  sns_smgr_periodic_report_resp_msg_v01     RSP,  *Rsp_p;
  int8_t  Dummy;
  
  Hdr_p = &HDR;
  Msg_p = &MSG;
  Rsp_p = &RSP;
  
  Hdr_p->client_id = 18;
  Hdr_p->priority = SNS_SMGR_REPORT_PRIORITY_LOW;

  Msg_p->ReportId = 6;
  Msg_p->Action = SNS_SMGR_REPORT_ACTION_ADD;
  Msg_p->ReportRate = 8;
  Msg_p->BufferFactor = 2;
  Msg_p->Item_len = 1;
  
  Msg_p->Item[0].SensorId = SNS_SMGR_ID_PRESSURE;  
  Msg_p->Item[0].DataType = SNS_SMGR_DATA_TYPE_ENG_UNITS;
  Msg_p->Item[0].Sensitivity = 80;
  Msg_p->Item[0].Decimation = SNS_SMGR_DECIMATION_FILTER;
  Msg_p->Item[0].MinSampleRate = 0; 
  Msg_p->Item[0].StationaryOption = SNS_SMGR_REST_OPTION_NO_REPORT;
  Msg_p->Item[0].DoThresholdTest = 0;
  Msg_p->Item[0].ThresholdOutsideMinMax = 0;
  Msg_p->Item[0].ThresholdDelta = 0;
  Msg_p->Item[0].ThresholdAllAxes = 0;
  Msg_p->Item[0].ThresholdMinMax[0] = 0;
  Msg_p->Item[0].ThresholdMinMax[1] = 0;
  
  
  sns_smgr_proc_periodic_req_msg( Hdr_p, Msg_p, Rsp_p );
  
  Dummy = 1;
}
#endif  /* TEST3 */	
  
#ifdef TEST4
{
  /* Add a high priority report when there is not enough available space.
     Should delete a lower priority report to make room. */
  sns_smgr_MsgHeader_s           HDR, *Hdr_p;
  sns_smgr_periodic_report_req_msg_v01  MSG,  *Msg_p;
  sns_smgr_periodic_report_resp_msg_v01     RSP,  *Rsp_p;
  int8_t  Dummy;
  
  Hdr_p = &HDR;
  Msg_p = &MSG;
  Rsp_p = &RSP;
  
  Hdr_p->client_id = 100;
  Hdr_p->priority = SNS_SMGR_REPORT_PRIORITY_HIGH;

  Msg_p->ReportId = 12;
  Msg_p->Action = SNS_SMGR_REPORT_ACTION_ADD;
  Msg_p->ReportRate = 115;
  Msg_p->BufferFactor = 2;
  Msg_p->Item_len = 1;
  
  Msg_p->Item[0].SensorId = SNS_SMGR_ID_GYRO;  
  Msg_p->Item[0].DataType = SNS_SMGR_DATA_TYPE_ENG_UNITS;
  Msg_p->Item[0].Sensitivity = 35;
  Msg_p->Item[0].Decimation = SNS_SMGR_DECIMATION_FILTER;
  Msg_p->Item[0].MinSampleRate = 0; 
  Msg_p->Item[0].StationaryOption = SNS_SMGR_REST_OPTION_NO_REPORT;
  Msg_p->Item[0].DoThresholdTest = 0;
  Msg_p->Item[0].ThresholdOutsideMinMax = 0;
  Msg_p->Item[0].ThresholdDelta = 0;
  Msg_p->Item[0].ThresholdAllAxes = 0;
  Msg_p->Item[0].ThresholdMinMax[0] = 0;
  Msg_p->Item[0].ThresholdMinMax[1] = 0;
  
  
  sns_smgr_proc_periodic_req_msg( Hdr_p, Msg_p, Rsp_p );
  
  Dummy = 1;
}
#endif  /* TEST4 */	
  
#ifdef TEST5
{
  /* Modify the 3 item, low priority report into a high priority
     report with a different number of items */
  sns_smgr_MsgHeader_s           HDR, *Hdr_p;
  sns_smgr_periodic_report_req_msg_v01  MSG,  *Msg_p;
  sns_smgr_periodic_report_resp_msg_v01     RSP,  *Rsp_p;
  int8_t  Dummy;
  
  Hdr_p = &HDR;
  Msg_p = &MSG;
  Rsp_p = &RSP;
  
  Hdr_p->client_id = 75;
  Hdr_p->priority = SNS_SMGR_REPORT_PRIORITY_HIGH;

  Msg_p->ReportId = 19;
  Msg_p->Action = SNS_SMGR_REPORT_ACTION_ADD;
  Msg_p->ReportRate = 1;
  Msg_p->BufferFactor = 3;
  Msg_p->Item_len = 1;
  
  Msg_p->Item[0].SensorId = SNS_SMGR_ID_GYRO;  
  Msg_p->Item[0].DataType = SNS_SMGR_DATA_TYPE_ENG_UNITS;
  Msg_p->Item[0].Sensitivity = 35;
  Msg_p->Item[0].Decimation = SNS_SMGR_DECIMATION_FILTER;
  Msg_p->Item[0].MinSampleRate = 100; 
  Msg_p->Item[0].StationaryOption = SNS_SMGR_REST_OPTION_NO_REPORT;
  Msg_p->Item[0].DoThresholdTest = 0;
  Msg_p->Item[0].ThresholdOutsideMinMax = 0;
  Msg_p->Item[0].ThresholdDelta = 0;
  Msg_p->Item[0].ThresholdAllAxes = 0;
  Msg_p->Item[0].ThresholdMinMax[0] = 0;
  Msg_p->Item[0].ThresholdMinMax[1] = 0;
  
  
  sns_smgr_proc_periodic_req_msg( Hdr_p, Msg_p, Rsp_p );
  
  Dummy = 1;
}  
#endif TEST5
  
#ifdef TEST6
{
  /* Add a slow report to test scheduling */
  sns_smgr_MsgHeader_s           HDR, *Hdr_p;
  sns_smgr_periodic_report_req_msg_v01  MSG,  *Msg_p;
  sns_smgr_periodic_report_resp_msg_v01     RSP,  *Rsp_p;
  int8_t  Dummy;
  
  Hdr_p = &HDR;
  Msg_p = &MSG;
  Rsp_p = &RSP;
  
  Hdr_p->client_id = 61;
  Hdr_p->priority = SNS_SMGR_REPORT_PRIORITY_LOW;

  Msg_p->ReportId = 1;
  Msg_p->Action = SNS_SMGR_REPORT_ACTION_ADD;
  Msg_p->ReportRate = 6;
  Msg_p->BufferFactor = 1;
  Msg_p->Item_len = 1;
  
  Msg_p->Item[0].SensorId = SNS_SMGR_ID_PRESSURE;  
  Msg_p->Item[0].DataType = SNS_SMGR_DATA_TYPE_ENG_UNITS;
  Msg_p->Item[0].Sensitivity = 80;
  Msg_p->Item[0].Decimation = SNS_SMGR_DECIMATION_FILTER;
  Msg_p->Item[0].MinSampleRate = 0; 
  Msg_p->Item[0].StationaryOption = SNS_SMGR_REST_OPTION_NO_REPORT;
  Msg_p->Item[0].DoThresholdTest = 0;
  Msg_p->Item[0].ThresholdOutsideMinMax = 0;
  Msg_p->Item[0].ThresholdDelta = 0;
  Msg_p->Item[0].ThresholdAllAxes = 0;
  Msg_p->Item[0].ThresholdMinMax[0] = 0;
  Msg_p->Item[0].ThresholdMinMax[1] = 0;
  
  
  sns_smgr_proc_periodic_req_msg( Hdr_p, Msg_p, Rsp_p );
  
  Dummy = 1;
}
#endif  /* TEST6 */	
  
  
#ifdef TEST7
{
  /* Add another slow report to test scheduling */
  sns_smgr_MsgHeader_s           HDR, *Hdr_p;
  sns_smgr_periodic_report_req_msg_v01  MSG,  *Msg_p;
  sns_smgr_periodic_report_resp_msg_v01     RSP,  *Rsp_p;
  int8_t  Dummy;
  
  Hdr_p = &HDR;
  Msg_p = &MSG;
  Rsp_p = &RSP;
  
  Hdr_p->client_id = 62;
  Hdr_p->priority = SNS_SMGR_REPORT_PRIORITY_LOW;

  Msg_p->ReportId = 2;
  Msg_p->Action = SNS_SMGR_REPORT_ACTION_ADD;
  Msg_p->ReportRate = 4;
  Msg_p->BufferFactor = 1;
  Msg_p->Item_len = 1;
  
  Msg_p->Item[0].SensorId = SNS_SMGR_ID_PRESSURE;  
  Msg_p->Item[0].DataType = SNS_SMGR_DATA_TYPE_ENG_UNITS;
  Msg_p->Item[0].Sensitivity = 80;
  Msg_p->Item[0].Decimation = SNS_SMGR_DECIMATION_FILTER;
  Msg_p->Item[0].MinSampleRate = 0; 
  Msg_p->Item[0].StationaryOption = SNS_SMGR_REST_OPTION_NO_REPORT;
  Msg_p->Item[0].DoThresholdTest = 0;
  Msg_p->Item[0].ThresholdOutsideMinMax = 0;
  Msg_p->Item[0].ThresholdDelta = 0;
  Msg_p->Item[0].ThresholdAllAxes = 0;
  Msg_p->Item[0].ThresholdMinMax[0] = 0;
  Msg_p->Item[0].ThresholdMinMax[1] = 0;
  
  
  sns_smgr_proc_periodic_req_msg( Hdr_p, Msg_p, Rsp_p );
  
  Dummy = 1;
}

#endif  /* TEST7 */	
  
#ifdef TEST8
{
/* Test scheduling */

int8_t Dummy;

  SmgrSchedHbeat();
  
  Dummy = 1;
}
#endif  

  
  return 0;
}
